# syntax=docker/dockerfile:1
FROM node:18-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copy and install dependencies configuration
COPY ./src/package.json .
RUN npm install

# Copy app source
COPY ./src/* .

# Open tcp port to outside
EXPOSE 5000

# Run node app
CMD [ "npm", "run", "start.dev" ]
